import type { UserIdType } from '../value-objects/userID.js'
import type { ChatIdType } from '../value-objects/chatID.js'

/**
 * The CHAT ID, a uuuidv7 string, is generated in the 'frontend' code
 * The UserID is found in the user's JWT token after authentication
 * It should be the same as the one stored in the database
 * There is not need to include created_at or created_at timestamps here
 * because they are generated by the database and not used in the business logic
 */

export class Chat {
  constructor(
    private readonly userId: UserIdType,
    public readonly id: ChatIdType
  ) {}

  /**
   * Gets the chat's unique identifier.
   *
   * @returns The chat's UUID
   *
   * @example
   * ```typescript
   * const chat = new Chat('user-123')
   * const id = chat.getId() // '01234567-89ab-cdef-0123-456789abcdef'
   * ```
   */
  getId(): ChatIdType {
    return this.id
  }

  /**
   * Gets the user ID associated with this chat.
   *
   * @returns The user's UUID who owns this chat
   *
   * @example
   * ```typescript
   * const chat = new Chat('user-123')
   * const userId = chat.getUserId() // 'user-123'
   * ```
   */
  getUserId(): UserIdType {
    return this.userId
  }
}
